-- CreateEnum
CREATE TYPE "BatchType" AS ENUM ('Check', 'Transmittal', 'CreditCard', 'ACH', 'NonCash', 'PayrollDeduction', 'Unknown');

-- CreateTable
CREATE TABLE "DailyDepartmentNotification" (
    "division" TEXT,
    "department" TEXT,
    "effective_date" DATE,
    "process_date" DATE,
    "pledged_date" DATE,
    "transaction_date" DATE,
    "transaction_type" TEXT NOT NULL,
    "donor1_amount" DECIMAL(65,30),
    "donor2_amount" DECIMAL(65,30),
    "combined_amount" DECIMAL(65,30) NOT NULL,
    "pledged_amount" DECIMAL(65,30) NOT NULL,
    "account_number" TEXT NOT NULL,
    "account_name" TEXT NOT NULL,
    "holding_destination" TEXT,
    "comment" TEXT,
    "sec_shares" TEXT,
    "sec_type" TEXT,
    "gik_type" TEXT,
    "gik_description" TEXT,
    "online_gift" BOOLEAN NOT NULL,
    "solicitation_code" TEXT,
    "solicitation" TEXT,
    "behalf_honor_memorial" TEXT,
    "matching_gift" TEXT,
    "batch_id" TEXT NOT NULL,
    "uk_first_gift" BOOLEAN NOT NULL,
    "div_first_gift" BOOLEAN NOT NULL,
    "id_sorter" TEXT NOT NULL,
    "combined_donor_name" TEXT NOT NULL,
    "combined_donor_salutation" TEXT NOT NULL,
    "combined_donor_sort" TEXT,
    "donor1_id" TEXT,
    "donor1_gift_key" TEXT,
    "donor1_name" TEXT,
    "donor1_deceased" BOOLEAN,
    "donor1_constituency" TEXT,
    "donor1_title_bar" TEXT,
    "donor1_pm" TEXT,
    "donor1_degrees" TEXT,
    "donor2_id" TEXT,
    "donor2_gift_key" TEXT,
    "donor2_name" TEXT,
    "donor2_deceased" BOOLEAN,
    "donor2_constituency" TEXT,
    "donor2_title_bar" TEXT,
    "donor2_pm" TEXT,
    "donor2_degrees" TEXT,
    "donor1_relation" TEXT,
    "donor2_relation" TEXT,
    "p_line1" TEXT,
    "p_line2" TEXT,
    "p_line3" TEXT,
    "p_city" TEXT,
    "p_state" TEXT,
    "p_zip" TEXT,
    "home_phone" TEXT,
    "home_phone_restriction" TEXT,
    "business_phone" TEXT,
    "business_phone_restriction" TEXT,
    "email" TEXT,
    "email_restriction" TEXT,
    "transmittal_sn" TEXT,
    "sap_doc_num" TEXT,
    "sap_doc_date" DATE,
    "jv_doc_num" TEXT,
    "jv_doc_date" DATE,
    "adv_fee_cc_phil" TEXT,
    "adv_fee_amt_phil" DECIMAL(65,30),
    "adv_fee_cc_unit" TEXT,
    "adv_fee_amt_unit" DECIMAL(65,30),
    "adv_fee_status" TEXT,
    "hc_unit" TEXT,

    CONSTRAINT "DailyDepartmentNotification_pkey" PRIMARY KEY ("id_sorter")
);

-- CreateTable
CREATE TABLE "DailyDepartmentNotificationBatch" (
    "batch_id" TEXT NOT NULL,
    "batch_type" "BatchType" NOT NULL,

    CONSTRAINT "DailyDepartmentNotificationBatch_pkey" PRIMARY KEY ("batch_id")
);

-- AddForeignKey
ALTER TABLE "DailyDepartmentNotification" ADD CONSTRAINT "DailyDepartmentNotification_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "DailyDepartmentNotificationBatch"("batch_id") ON DELETE RESTRICT ON UPDATE CASCADE;
