name: "Promote EAS"
description:
  "Take the latest EAS build from one branch and promote it to another"
inputs:
  from-branch:
    description: "Branch to promtoe from"
    required: true
  to-branch:
    description: "Branch to promtoe to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get EAS Update group id for from group
      run:
        echo "groupId=$(npx eas-cli update:list --limit=1 --branch=${{
        inputs.from-branch }} --non-interactive --json | jq
        .currentPage[0].group -r)" >> $GITHUB_ENV
      shell: bash
    - name: Get EAS Update group commit for to group
      run:
        echo "groupCommit=$(npx eas-cli update:view --json ${{ env.groupId }} |
        jq .[0].gitCommitHash -r)" >> $GITHUB_ENV
      shell: bash
    - name: Get EAS Update group id for to group
      run:
        echo "groupId=$(npx eas-cli update:list --limit=1 --branch=${{
        inputs.to-branch }} --non-interactive --json | jq .currentPage[0].group
        -r)" >> $GITHUB_ENV
      shell: bash
    - name: Get EAS Update group commit for to group
      run:
        echo "groupCommit=$(npx eas-cli update:view --json ${{ env.groupId }} |
        jq .[0].gitCommitHash -r)" >> $GITHUB_ENV
      shell: bash
    - name: Promote EAS Update
      if: ${{ env.fromGroupCommit }} != ${{ env.toGroupCommit }}
      run:
        npx eas-cli update:republish --group=${{ env.groupId }}
        --destination-branch=${{ inputs.to-branch }} --non-interactive
        --message="Promote ${{ inputs.from-branch }} to ${{ inputs.to-branch }}"
      shell: bash
