name: EAS Update Preview

on:
  pull_request:
    branches: ["main"]
    paths:
      - "packages/common/**"
      - "packages/mobile/**"
      - "yarn.lock"
      - ".yarnrc.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Set up node 22.x
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        timeout-minutes: 1

      - name: Install dependencies
        run: yarn install

      - name: Build common
        run: yarn workspace @ukdanceblue/common run build

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command:
            eas update --auto --branch ${{ github.event.pull_request.head.ref }}
          working-directory: packages/mobile
