name: Promote Staging To Release

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 or 2 AM Eastern Time
    - cron: "0 6 * * *"

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  promote-eas-update:
    name: Promote EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - name: Set up node 22.x
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22
          cache: yarn
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn workspaces focus @ukdanceblue/mobile
      - name: Promote release
        run: ./scripts/promote-eas-update.sh staging release
  promote-docker:
    name: Promote Docker
    environment:
      name: release
      url: https://app.danceblue.org
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote release
        run: ./scripts/promote-docker.sh staging release
      - name: Update the deployment
        run: curl --data {} ${{ secrets.DEPLOY_WEBHOOK }}
