name: Promote Staging

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 or 2 AM Eastern Time
    - cron: "0 6 * * *"

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  do-release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://app.danceblue.org
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Promote
        uses: ./promote.yml
        with:
          from: staging
          to: release
