name: Promote Staging

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 or 2 AM Eastern Time
    - cron: "0 6 * * *"

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  do-release:
    uses: ./.github/workflows/promote.yml
    with:
      from: staging
      to: release
