name: Stage Release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  stage-release:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://stg.danceblue.org
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Promote
        uses: ./promote.yml
        with:
          from: main
          to: staging
