name: Stage Release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  stage-release:
    uses: ./.github/workflows/promote.yml
    with:
      from: main
      to: staging
