name: Test

on:
  push:
    branches:
      - main
    paths:
      [
        "packages/**",
        "vitest.workspace.ts",
        "package.json",
        "yarn.lock",
        ".yarnrc.yml",
        "tsconfig.json",
        ".github/workflows/test.yml",
      ]
  pull_request:
    branches:
      - main
    paths:
      [
        "packages/**",
        "vitest.workspace.ts",
        "package.json",
        "yarn.lock",
        ".yarnrc.yml",
        "tsconfig.json",
      ]
  workflow_call:

jobs:
  run-tests:
    name: Test Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Set up node 22.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: yarn run server:prisma generate

      - name: Build common
        run: yarn run common:build

      - name: Run Tests
        run: yarn repo:test --run
